# Project information

site_name: Data Protection on AWS
site_short_name: Data Protection
site_description: 'Workshop and sample code that builders can use for experiential learning of AWS services that provide data protection. Services such as AWS KMS, AWS ACM, Amazon Macie, AWS CloudHSM and others will be explored'
site_author: 'aws-security-workshops@amazon.com'
site_url: 'https://data-protection.awssecworkshops.com'

# Repository
repo_name: 'aws-samples/data-protection'
repo_url: 'https://github.com/aws-samples/data-protection'

# Copyright
copyright: '&copy; 2019, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/aws_smile_logo.png'
  favicon: 'assets/images/aws-favicon.ico'
  feature:
    tabs: true
  custom_dir: 'docs/theme'

# Customization
extra_css:
  - 'stylesheets/custom.css'
extra:
  social:
    - type: 'home'
      link: 'https://awssecworkshops.com'
    - type: 'shield'
      link: 'https://aws.amazon.com/security/'
    - type: 'twitter'
      link: 'https://twitter.com/awssecurityinfo?lang=en'
    - type: 'rss'
      link: 'https://aws.amazon.com/blogs/security/'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details

# Navigation
nav:
  - Overview: 'index.md'
  - Contributing: 'contribute.md'
  - License: 'license.md'